config/routes.rb
Rails.application.routes.draw do

  resources :messages

  root 'messages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :nick, presence: true, length: {minimum: 2}
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messageslast = Message.last(50)
    @message = Message.new
  end

  def create
    @message = Message.new(messages_params)

    @message.save

    redirect_to :back
  end
end

private
def messages_params
  params.require(:message).permit(:nick,:content)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="fut">
 Made by Lukashman in 2017
</footer>

app/views/layouts/_header.html.erb
<header class="nav navbar-fixed-top navbar-inverse logo">
  Welcome to my special chat
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/header' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<title>Simple chat</title>
<%= render 'layouts/header' %>
<div class="chat pre-scrollable">
<% @messageslast.each do |d| %>
<chats class="nic"><%= d.nick%>:</chats>  <%= d.content %><br>
<% end %>
</div>
<div class="cross">
<%= form_for :message, url: messages_path do |f| %>
    <p>
      <%= f.label "Ник" %>
      <%= f.text_field :nick%>
    </p>

    <p>
      <%= f.label "Содержание" %>
      <%= f.text_area :content%>
    </p>

    <p class="btn-default">
      <%= f.submit%>
    </p>
      </div>
      <%= render 'layouts/footer' %>
<% end %>